FROM node:18-alpine

WORKDIR /workspace

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json
COPY tsconfig.base.json ./tsconfig.base.json
COPY tsconfig.json ./tsconfig.json
COPY turbo.json ./turbo.json

RUN npm install

COPY . ./

WORKDIR /workspace/frontend

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
